# Generated by Django 5.2.8 on 2025-11-29 09:16

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='sub_role',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='body_member_position',
            field=models.CharField(blank=True, choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('MEMBER', 'Member')], help_text='Position in the church body (if is_body_member is True)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='families.family'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='is_body_member',
            field=models.BooleanField(default=False, help_text='Is this user a member of the church body/committee?'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='phone_number',
            field=models.CharField(help_text='10-digit Indian mobile number starting with 6-9. Used for WhatsApp.', max_length=10, unique=True, validators=[accounts.models.validate_indian_mobile]),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('PARISH_PRIEST', 'Parish Priest'), ('FAMILY_HEAD', 'Family Head'), ('FAMILY_MEMBER', 'Family Member')], default='FAMILY_HEAD', max_length=20),
        ),
    ]
