# Generated by Django 5.2.8 on 2025-11-29 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'The Smith Family'", max_length=100)),
                ('family_head', models.OneToOneField(limit_choices_to={'role': 'FAMILY_HEAD'}, on_delete=django.db.models.deletion.CASCADE, related_name='headed_family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
